# Generated by Django 6.0.4 on 2026-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('accept', models.BooleanField()),
            ],
        ),
    ]
