# Generated by Django 6.0.4 on 2026-06-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
