# Generated by Django 6.0.4 on 2026-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_users_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='regestration',
            field=models.DateField(default='2002-04-13'),
            preserve_default=False,
        ),
    ]
