# Generated by Django 6.0.4 on 2026-06-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_users_regestration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='SMS_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users', to_field='number')),
            ],
        ),
    ]
